Service tracing and error handling
mprudnik/node-soa-template pull request #5
Opened 2023-01-25 09:54 UTC by mprudnik

- added wrapper to service commands and event handlers
- added error handling inside wrapper
- added `operationId` propagation to be able to trace child calls to bus `publish` and `command`

Current implementation allows to easily extend wrapper to support `command`/`eventHandler` level hooks

2023-02-04 12:44 UTC, georgolden requested changes

2023-02-04 12:44 UTC, georgolden commented on src/server/server.js
> +        { meta: { definition }, data: { token } },
insconsistent naming -> refernces to auth property in a route

2023-02-04 12:44 UTC, georgolden commented on src/server/plugins/http/http.js
> +            return res.code(code).send({ message });
move to a seperate http specific error handling abstraction or use fatistify hooks for error handling

2023-02-04 12:44 UTC, georgolden commented on src/infra/bus.js
> +    return handler({ ...payload, meta: wrappedMeta });
If you want to use [error, result] contract - better to wrap outside, whenever a command called

2023-02-04 12:44 UTC, georgolden commented on src/services/account/account.js
> +    meta: {},
meta must be optional

2023-02-04 12:44 UTC, georgolden commented on src/services/services.js
> +};
Here is optional metadata injection withing bus using Proxy and partial application function
https://github.com/georgolden/node-soa/blob/wip-fucntional-style/src/infra/nodeBus.js
I use this during domain function creation - in your case it is a name of a command handler or event handler
https://github.com/georgolden/node-soa/blob/wip-fucntional-style/src/dfs/domainFunction.js

2023-02-20 15:08 UTC, mprudnik commented
Done in https://github.com/mprudnik/node-soa-template/pull/6/commits/fe37d7c36df33075e23857e73c3257745a4a2097.

2023-02-20 15:08 UTC, closed without merging